# Generated by Django 5.0.6 on 2024-05-15 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_alter_newsletter_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
