# Generated by Django 5.0.4 on 2024-05-10 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_ticketreply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketreply',
            options={'get_latest_by': 'date_reply'},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
